### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by s-pangburn** [masonanders/SoundWaves#1]
## MVP List

- [x] "MVPs" not "MPVs" 😂 
- [x] You should list out the particulars of each feature (CRUD, styling, options, etc)
  - [x] [Use the bluebird wiki as a formatting reference](https://github.com/appacademy/bluebird/wiki/mvp-list)

---

## Database Schema

- [x] Column names and table titles should be formatted with `backticks`.
- [x] Include bullet points for indexes and unique constraints at the database level.
- [x] You'll probably be using ActiveStorage for this project, which means you technically won't be needing `image_url` columns for users, tracks, or playlists (it will work through associations eventually).

---

## Backend Routes

- [x] You should include your HTTP verbs (`GET`, `POST`, etc) with your routes and they should be formatted [like this](https://github.com/appacademy/bluebird/wiki/backend-routes)
  - [x] In particular, make sure you include the CRUD routes for the features that will have it!
- [x] Wildcards are conventionally denoted like this: `:id` instead of this: `{id}`

---

## Frontend Routes and Components

- [x] These are good! However, the way we prefer you to format this page is with the routes and components [grouped together](https://github.com/appacademy/bluebird/wiki/frontend-routes), where it is clear what components are rendering at which routes.
- [x] Also, `backticks` like the link I just gave you!

---

## Sample State

- [x] Put ```js at the top of the code block to enable syntax highlighting!
- [x] You won't need lists of ids for `likes` in your `users` slice of state, since `likes` is a joins table. You'll just find the relevant like by userId. This goes for all joins you plan to have in your app (`genreTags`, `playlistTracks`, etc.)

Be sure to get to these changes before tomorrow so that you can hit the ground running! 

Let me know if you have any questions :slightly_smiling_face:

**Comment by masonanders** [comment]
Not sure how I missed MPVs -.- Thanks for the feedback

**Comment by masonanders** [comment]
I've checked off each item but not sure if I'm supposed to close the issue or you are

**Comment by s-pangburn** [comment]
I am! Any time you open a PA Review or I open an issue, you can comment here to let me know you're done and I can close the issue to show I approved the fixes 🙂 

If you want to open your own issues though, of course, feel free to close them yourself. You don't need my approval for those.

That being said, I'll close this issue. Good job Mason!

**Comment by masonanders** [comment]
Awesome, thanks!
