### ISSUE TITLE
MVP Complete - Song CRUD

### ISSUE THREAD

**Issue by masonanders** [masonanders/SoundWaves#4]
## 1. Song CRUD

- [x] Upload tracks
- [x] Setup AWS production
- [x] Track upload page
- [x] Track show page
- [x] Track index feed
- [x] Update/delete user's own tracks
- [x] Tracks play audio, can pause.
- [x] Finish styling index
- [x] Finish styling show
- [x] Finish styling upload

**Comment by masonanders** [comment]
I made it to MPV #2!!!

**Comment by s-pangburn** [comment]
Looking really good Mason! Great work!

- [x] Your "Edit/Delete this track?" Yes button does not `cursor: pointer` (but your No button does) 
- [x] When I delete a track, I get a blank page and this error in the console (I'm also still at `:user/:track_name`:
![screen shot 2018-08-16 at 9 52 50 am](https://user-images.githubusercontent.com/8031316/44222690-3558fe80-a13a-11e8-8752-5b8422b13750.png)
- [x] Editing a track, then pressing the back button takes you to a blank song page (I'm assuming this was the previous song?) If you're using `history.push` to change the url, this might be a simple fix: use `history.replace` instead, which will overwrite the current url in the history.
- [x] This has more to do with your Song Playback MVP but I can't resume a song after editing.
- [x] The little icon next to the progress bar doesn't do anything when you first arrive to the site. It probably shouldn't be there until a song is playing?
- [x] Editing a track name to be somewhat long leads to this:
![screen shot 2018-08-16 at 10 04 20 am](https://user-images.githubusercontent.com/8031316/44223219-d8f6de80-a13b-11e8-8101-55daa036a071.png)

**Comment by s-pangburn** [comment]
👏 👏 👏
